clinic/urls.py
from django.urls import path

from . import views

app_name = "clinic"
urlpatterns = [
    ############## home page ##############
    path("", views.home, name="home"),
    ############## patient handling ##############
    path("patient_list/", views.patient_list, name="patient_list"),
    path(
        "patient_list/<int:pk>/",
        views.patient_data,
        name="patient_data",
    ),
    path(
        "patient_list/register_patient/",
        views.register_patient,
        name="register_patient",
    ),
    ############## medical record handling ##############
    path(
        "patient_list/<int:pk>/add_medical_record/",
        views.add_medical_record,
        name="add_medical_record",
    ),
    ############## appointment handling ##############
    path(
        "patient_list/<int:pk>/add_appointment/",
        views.add_appointment,
        name="add_appointment",
    ),
    path("appointment_list/", views.appointment_list, name="appointment_list"),
    path("today_appointment/", views.today_appointment, name="today_appointment"),
    path("future_appointment/", views.future_appointment, name="future_appointment"),
    ############## check in handling ##############
    path("checkin_list/", views.checkin_list, name="checkin_list"),
    path("checkin_table/", views.checkin_table, name="checkin_table"),
    path(
        "patient_list/<int:pk>/patient_checkin/",
        views.add_checkin,
        name="patient_checkin",
    ),
    path(
        "appointment_list/<int:pk>/checkin_list/",
        views.move_to_checkin,
        name="move_to_checkin",
    ),
    ############## payment handling ##############
    path(
        "checkin_list/<int:checkin_pk>/payment/",
        views.customer_payment,
        name="payment",
    ),
    ############## Inventory handling ##############
    path("inventory_list/", views.inventory_list, name="inventory_list"),
    path(
        "inventory_list/<int:pk>/add_stock/",
        views.add_item_into_inventory,
        name="add_stock",
    ),
]

clinic_management_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("clinic.urls")),
    path("", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinic/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Profile

from datetime import date

# Create your models here.
TITLE_CHOICES = {
    1: "Mr.",
    2: "Mrs.",
    3: "Ms.",
}


class Patient(models.Model):
    class Meta:
        permissions = [
            ("can_register", "Can register new patient"),
        ]

    title = models.IntegerField(choices=TITLE_CHOICES, default=1, blank=True, null=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    ic_number = models.CharField(max_length=12, unique=True)
    email = models.EmailField(max_length=100, null=True, blank=True, unique=True)
    phone_number = models.CharField(max_length=20, unique=True)
    register_date = models.DateTimeField(
        verbose_name="register_date", default=timezone.now
    )

    def __str__(self):
        return self.first_name


class Medicine(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    dosage_form = models.CharField(max_length=50)
    indication = models.CharField(max_length=50)
    strength = models.IntegerField(default=1)  # in mg
    quantity_in_stock = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.name} {self.strength}mg"


class Appointment(models.Model):
    TIMESLOT_LIST = {
        0: "9:00 - 10:00",
        1: "10:00 - 11:00",
        2: "11:00 - 12:00",
        3: "12:00 - 01:00",
        # doctor lunch break 1pm - 3pm
        4: "03:00 - 04:00",
        5: "04:00 - 05:00",
        6: "05:00 - 06:00",
    }

    STATUS_LISTS = {
        1: "Scheduled",
        2: "Completed",
        3: "No Show",
    }

    class Meta:
        # patient, timeslot and date have to be unique
        unique_together = ["time_slot", "date"]

    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    time_slot = models.IntegerField(choices=TIMESLOT_LIST)
    status = models.IntegerField(choices=STATUS_LISTS, default=1)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.description


class MedicalRecord(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    medicine = models.ManyToManyField(Medicine, blank=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    record_date = models.DateTimeField(verbose_name="record_date", default=timezone.now)
    medical_leave = models.IntegerField(
        default=0
    )  # to record if patient get any medical leaves
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.doctor.user_type != Profile.UserType.DOCTOR:
            raise ValueError("Selected user is not a doctor.")
        super().save(*args, **kwargs)


class Checkin(models.Model):
    CHECKIN_STATUS = {
        1: "waiting",
        2: "done",
    }
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    status = models.IntegerField(choices=CHECKIN_STATUS, default=1)
    date = models.DateField(auto_now_add=True)
    medical_record = models.OneToOneField(
        MedicalRecord, on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return f"{self.patient.first_name} checkin at {self.date}"


class Payment(models.Model):
    PAYMENT_STATUS = {
        1: "unpaid",
        2: "paid",
    }
    PAYMENT_TYPE = {
        1: "cash",
        2: "card",
    }
    medical_record = models.OneToOneField(MedicalRecord, on_delete=models.CASCADE)
    payment_status = models.IntegerField(choices=PAYMENT_STATUS, default=1)
    payment_type = models.IntegerField(choices=PAYMENT_TYPE, default=1)
    payment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment for {self.medical_record.title} - Status: {self.get_payment_status_display()} "

clinic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db import IntegrityError, transaction
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Patient, MedicalRecord, Appointment, Checkin, Payment, Medicine
from accounts.models import Profile
from .forms import (
    PatientRegistrationForm,
    MedicalRecordUpdateForm,
    AddAppointmentForm,
    PaymentForm,
    InventoryAddItemForm,
)

from accounts.decorators import allowed_users

from datetime import date


########################### home page ################################


@login_required
def home(request):
    today = date.today()

    appointment_count = Appointment.objects.filter(date=today).count()
    checkin_count = Checkin.objects.filter(date=today).count()

    context = {
        "title": "Home",
        "appointment_count": appointment_count,
        "checkin_count": checkin_count,
        "user": request.user,
    }
    return render(request, "clinic/index.html", context)


########################### patient handling ################################


@login_required
def patient_list(request):
    query = request.GET.get("search", "")
    if query:
        patients = Patient.objects.filter(
            Q(first_name__icontains=query) | Q(last_name__icontains=query)
        )
    else:
        patients = Patient.objects.all()

    context = {
        "patients": patients,
        "search_query": query,
        "title": "Patient List",
    }

    return render(request, "clinic/patient_list.html", context)


@login_required
def patient_data(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    medical_records = MedicalRecord.objects.filter(patient=patient).order_by(
        "-record_date"
    )
    past_appointments = Appointment.objects.filter(patient=patient, status__in=[2, 3])
    context = {
        "medical_records": medical_records,
        "past_appointments": past_appointments,
        "patient": patient,
        "title": f"{patient.first_name} Details",
    }
    return render(request, "clinic/patient_details.html", context)


"""This function can be accessed only by staff and admin"""


@login_required
@allowed_users(
    message="You do not have permission to register new patient.",
    redirect_link="clinic:patient_list",
    allowed_user_types=[Profile.UserType.ADMIN, Profile.UserType.CLINIC_STAFF],
)
def register_patient(request):
    if request.method == "POST":
        form = PatientRegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            form.save()
            messages.success(request, f"{first_name} registered.")
            return redirect("clinic:home")
    else:
        form = PatientRegistrationForm()

    context = {
        "form": form,
        "title": "Patient Registration",
    }

    return render(request, "clinic/register_patient.html", context)


########################### medical records handling ################################
@login_required
@allowed_users(
    "You do not have permission to add medical record.",
    redirect_link="clinic:checkin_list",
    allowed_user_types=[Profile.UserType.DOCTOR, Profile.UserType.ADMIN],
)
def add_medical_record(request, pk):
    today = date.today()

    """get checkin by patient id, status:waiting and date: today"""
    checkin = Checkin.objects.get(patient_id=pk, status=1, date=today)

    """check if user has no profile, usually super user which create with command line"""
    if not hasattr(request.user, "profile"):
        messages.error(
            request,
            "You do not have a profile. If you're superuser, you can access this using admin page.",
        )
        return redirect("clinic:checkin_list")

    """check if medical record already updated,
    to make sure that there's no duplicate medical record in one checkin"""
    if checkin.medical_record:
        messages.error(
            request, "A medical record has already been added for this check-in."
        )
        return redirect("clinic:checkin_list")

    form = MedicalRecordUpdateForm()

    if request.method == "POST":
        form = MedicalRecordUpdateForm(request.POST)
        if form.is_valid():
            medicines = form.cleaned_data.get("medicines")
            stock_error = False

            # Check for stock availability
            for med in medicines:
                if med.quantity_in_stock <= 0:
                    messages.error(request, f"Not enough stock for {med.name}!")
                    stock_error = True

            if stock_error:
                return render(
                    request,
                    "clinic/add_medical_record.html",
                    {"form": form, "checkin": checkin, "title": "Medical Record"},
                )

            record_title = form.cleaned_data.get("title")
            record = form.save(commit=False)
            record.patient = checkin.patient
            record.doctor = request.user.profile

            try:
                # Save each medicine record and update stock
                with transaction.atomic():
                    record.save()
                    record.medicine.set(medicines)  # save medicines into record

                    """update the stock quantity of each medicine selected for this record"""
                    for med in medicines:
                        med.quantity_in_stock -= 1
                        med.save()

                    """update checkin instance"""
                    checkin.medical_record = record
                    checkin.status = 2
                    checkin.save()

                messages.success(request, f"{record_title} added.")
                return redirect("clinic:checkin_list")
            except ValueError as e:
                messages.error(request, str(e))
                return render(
                    request,
                    "clinic/add_medical_record.html",
                    {"form": form, "checkin": checkin, "title": "Medical Record"},
                )
    else:
        form = MedicalRecordUpdateForm()

    context = {
        "form": form,
        "checkin": checkin,
        "title": "Medical Record",
    }

    return render(request, "clinic/add_medical_record.html", context)


########################### appointment handling ################################
@login_required
def appointment_list(request):
    context = {
        "title": "List Of Appointment",
    }
    return render(request, "clinic/appointment_list.html", context)

@login_required
def today_appointment(request):
    today = date.today()
    today_appointment = Appointment.objects.filter(date=today)

    context = {
        "today_appointment" : today_appointment,
    }

    return render(request, "clinic/partials/today_appointment_table.html", context)

@login_required
def future_appointment(request):
    today =date.today()
    future_appointment = Appointment.objects.filter(date__gt=today).order_by("date")

    context = {
        "future_appointment": future_appointment,
    }

    return render(request, "clinic/partials/future_appointment_table.html", context)


@login_required
@allowed_users(
    "You do not have permission to add new appointment.",
    redirect_link="clinic:patient_list",
    allowed_user_types=[Profile.UserType.CLINIC_STAFF, Profile.UserType.ADMIN],
)
def add_appointment(request, pk):
    patient = get_object_or_404(Patient, pk=pk)

    if request.method == "POST":
        form = AddAppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.patient = patient
            try:
                appointment.save()
                messages.success(request, f"appointment added.")
                return redirect("clinic:patient_data", pk=pk)
            except IntegrityError:
                messages.info(request, "Already existed")
                return redirect("clinic:patient_data", pk=pk)
    else:
        form = AddAppointmentForm()

    context = {
        "patient": patient,
        "form": form,
        "title": "Add Appointment",
    }

    return render(request, "clinic/add_appointment.html", context)


@login_required
@allowed_users(
    "You do not have permission to move patient into check-in list.",
    redirect_link="clinic:checkin_list",
    allowed_user_types=[Profile.UserType.CLINIC_STAFF, Profile.UserType.ADMIN],
)
def move_to_checkin(request, pk):
    """Handle moving patients to check-in from the appointment list."""
    today = date.today()
    appointment = get_object_or_404(Appointment, pk=pk)

    # Ensure the appointment is for today
    if appointment.date != today:
        messages.error(
            request, "You can only check in patients with today's appointment."
        )
        return redirect("clinic:appointment_list")

    # Check if a check-in already exists for today with status "waiting"
    existing_checkin = Checkin.objects.filter(
        patient=appointment.patient, date=today, status=1
    ).exists()

    if existing_checkin:
        messages.info(request, "Patient is already checked in and waiting.")
        return redirect("clinic:appointment_list")

    # Check if the patient has already checked in today but the status is "done"
    previous_checkin = (
        Checkin.objects.filter(patient=appointment.patient, date=today)
        .exclude(status=1)
        .exists()
    )

    if previous_checkin:
        messages.info(
            request,
            "Patient has completed a previous check-in but can be re-checked in.",
        )

    checkin = Checkin.objects.create(
        patient=appointment.patient,
        status=1,
        date=today,
    )

    """change appointment status to Completed so that I can disabled to button/link"""
    appointment.status = 2

clinic/templates/clinic/partials/checkin_table.html
<!-- clinic/templates/clinic/checkin_table.html -->
<table class="table table-striped">
    <thead>
        <tr class="table-info">
            <th>#</th>
            <th>Full Name</th>
            <th>Date</th>
            <th>Handle</th>
            <th>Status</th>
            <th>Payment</th>
        </tr>
    </thead>
    <tbody>
        {% for checkin in checkin_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ checkin.patient.first_name|title }} {{ checkin.patient.last_name|title }}</td>
            <td>{{ checkin.date }}</td>
            <td>
                {% if checkin.medical_record %}
                <a href="{% url 'clinic:add_medical_record' checkin.patient.pk %}"
                    class="btn btn-success rounded-pill btn-sm disabled">
                    Medical Record Added
                </a>
                {% else %}
                <a href="{% url 'clinic:add_medical_record' checkin.patient.pk %}"
                    class="btn btn-primary rounded-pill btn-sm">
                    Add Medical Record
                </a>
                {% endif %}
            </td>
            <td>
                {% if checkin.get_status_display == "waiting" %}
                <p class="text-primary">
                    {{ checkin.get_status_display|title }}
                </p>
                {% elif checkin.get_status_display == "done" %}
                <p class="text-success">
                    {{ checkin.get_status_display|title }}
                </p>
                {% endif %}
            </td>
            <td>
                {% if checkin.medical_record %}
                {% if checkin.medical_record.payment %}
                <a href="{% url 'clinic:payment' checkin.pk %}" class="btn btn-success rounded-pill btn-sm disabled">
                    RM{{ checkin.medical_record.price }}
                </a>
                {% else %}
                <a href="{% url 'clinic:payment' checkin.pk %}" class="btn btn-primary rounded-pill btn-sm">
                    RM{{ checkin.medical_record.price }}
                </a>
                {% endif %}
                {% else %}
                <a href="{% url 'clinic:payment' checkin.pk %}" class="btn btn-primary rounded-pill btn-sm disabled">
                    RM0.00
                </a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="6">No Check-in Found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

clinic/templates/clinic/partials/future_appointment_table.html
<table class="table table-striped">
    <thead>
        <tr class="table-secondary">
            <th scope="col">No</th>
            <th scope="col">Patient</th>
            <th scope="col">Time Slot</th>
            <th scope="col">Date</th>
            <th scope="col">Check-In</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in future_appointment %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ appointment.patient.first_name }} {{ appointment.patient.last_name }}</td>
            <td>{{ appointment.get_time_slot_display }}</td>
            <td>{{ appointment.date }}</td>
            {% if appointment.get_status_display == "Completed" %}
            <td>
                <a href="{% url 'clinic:move_to_checkin' appointment.pk %}"
                    class="btn btn-success rounded-pill btn-sm disabled">
                    Moved
                </a>
            </td>
            {% else %}
            <td>
                <a href="{% url 'clinic:move_to_checkin' appointment.pk %}"
                    class="btn btn-primary rounded-pill btn-sm disabled">
                    Move
                </a>
            </td>

            {% endif %}
            {% if appointment.get_status_display == "Scheduled" %}
            <td>
                <p class="text-primary">
                    {{ appointment.get_status_display }}
                </p>
            </td>
            {% else %}
            <td>
                <p class="text-success">
                    {{ appointment.get_status_display }}
                </p>
            </td>

            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

clinic/templates/clinic/partials/today_appointment_table.html
<table class="table table-striped">
    <thead>
        <tr class="table-info">
            <th scope="col">No</th>
            <th scope="col">Patient</th>
            <th scope="col">Time Slot</th>
            <th scope="col">Date</th>
            <th scope="col">Check-In</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in today_appointment %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ appointment.patient.first_name }} {{ appointment.patient.last_name }}</td>
            <td>{{ appointment.get_time_slot_display }}</td>
            <td>{{ appointment.date }}</td>
            {% if appointment.get_status_display == "Completed" %}
            <td>
                <a href="{% url 'clinic:move_to_checkin' appointment.pk %}"
                    class="btn btn-success rounded-pill btn-sm disabled">
                    Moved
                </a>
            </td>
            {% else %}
            <td>
                <a href="{% url 'clinic:move_to_checkin' appointment.pk %}" class="btn btn-primary rounded-pill btn-sm">
                    Move
                </a>
            </td>

            {% endif %}
            {% if appointment.get_status_display == "Scheduled" %}
            <td>
                <p class="text-primary">
                    {{ appointment.get_status_display }}
                </p>
            </td>
            {% else %}
            <td>
                <p class="text-success">
                    {{ appointment.get_status_display }}
                </p>
            </td>

            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>